keys:
  # User's SSH public key
  - &alex ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNU3LlO+b/kYovYE8CYSa2gExOw0hdCytCiziwIf3a6DVGGLsLELOwTcrUCr+ysnU6nUQT2JPrJCowB/wXx5X0Rcxv6+ZG/WxSukT858PEjKKt6nHp84NhsltidMLOw4kDL257M7CAXhMhVXvxW369jhYNM54tT/Tl2pMPKk0AeVd+RJGkJCjVAvmvX9W1YeggWYx9RgDYHlS3u4l0kTOpNVZQ+8SWeuPqsg52r7bh9biA3snb63UUaOSSgCQAKXS11S1SLu7XcYjk9A8vIqMbFGeu738/sn4THOn7Nq10hvbqQH9jIt4sfSq7LcQF8xXponv2P1PbYxYFsFWqABTBQXtrrQTpP+mlK2/eruuQRLcrNrmEoX05pCzZ2utGJh0mxLbIeMBRRc68CuFq0wxpCmPRjhPapLCM73ZPf26TEwS0dgHzQkX0ZJDOUBXyzBrniIdDV5KG52Fo4o7pM6i6t+BGQtVM9pqoGQOQGOsNq862n+liRQ8r3MjgDc9rxPHcs5ieA6RT4k9OnBW+UGiDx3W32iuyfc92WUm3Kdrj8+lfWnz6805cKt1UPUU0vK6tl4wZq64TdF2aBkllulTUP8ecLx0r/Mdw6ulXkA3rmj6wE6dJ3kigYGhOHWkck3AGQI9CX8EyjeGO3V4MVOx+BQpyqwtjKHefe9SjBcYHYQ==

  # Target hosts
  - &xcloud_postgres age1yj47k38v43yepgl90f3zf69x9pa4d0r62lea2m6pyc4c20uvxa0q0ypetr
  - &xcloud_caddy age1s5sgpa5e0mdsk35el9ht3e2c7kaug6nllu66s8yqysqvaetug9tsawghl0
  - &proxmox_gitlab age1fpln6gutf0p4rxdrt68ttt92987fzs2v9m9qmh03p2jssf26q9qskxqw0n
  - &proxmox_video age1urv48kam9uktkf82yfj4nyytaxx72menqxvycttwsrw69m6hj58ssxqd3v
  - &proxmox_observability age1mfqluv6rpa2qx4vz9ym247v48sqra882vy0qhezqml0xex2853nseph3gm

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *alex
          - *xcloud_postgres
          - *xcloud_caddy
          - *proxmox_gitlab
          - *proxmox_video
          - *proxmox_observability
