#!/usr/bin/env bash
# Emit a GitLab child-pipeline YAML that fills, verifies, and (on --deploy)
# switches only the hosts in changed-hosts.json. Templates live in
# ci/jobs.yml so this file does not duplicate SSH / ATTIC_SKIP_FILL.
#
# Usage: ./scripts/gitlab-gen-pipeline.sh [--deploy] [-o out.yml] changed-hosts.json
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

DEPLOY=0
OUT="/dev/stdout"
JSON=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --deploy)
      DEPLOY=1
      shift
      ;;
    -o)
      OUT="$2"
      shift 2
      ;;
    -*)
      echo "Usage: $0 [--deploy] [-o out.yml] changed-hosts.json" >&2
      exit 1
      ;;
    *)
      JSON="$1"
      shift
      ;;
  esac
done

if [ -z "$JSON" ]; then
  echo "Usage: $0 [--deploy] [-o out.yml] changed-hosts.json" >&2
  exit 1
fi

python3 - "$JSON" "$OUT" "$DEPLOY" "${CI_PROJECT_PATH:-}" "${CI_COMMIT_SHA:-}" <<'PY'
import json
import sys

src, dest, deploy_flag = sys.argv[1], sys.argv[2], sys.argv[3] == "1"
project = sys.argv[4] if len(sys.argv) > 4 else ""
ref = sys.argv[5] if len(sys.argv) > 5 else ""

with open(src, encoding="utf-8") as f:
    data = json.load(f)

x86 = list(data.get("x86") or [])
rpi4 = list(data.get("rpi4") or [])
gaming = list(data.get("gaming") or [])

# `include: local:` should resolve against this pipeline's own project/ref
# even when the including file is itself an artifact (dynamic child
# pipeline), per GitLab's documented behavior. This project+ref form is
# an explicit, defensive equivalent: it does not depend on that artifact
# resolution behavior and instead names project/ref outright. CI_PROJECT_PATH
# and CI_COMMIT_SHA are always set inside a real job; both are empty when
# this script runs locally (e.g. for the dry-runs below), so local runs
# fall back to the plain form.
if project and ref:
    include_block = [
        "include:",
        f"  - project: {project}",
        f"    ref: {ref}",
        "    file: /ci/jobs.yml",
    ]
else:
    include_block = [
        "include:",
        "  - local: ci/jobs.yml",
    ]

lines = [
    "# Generated by scripts/gitlab-gen-pipeline.sh. Do not edit.",
    *include_block,
    "",
    "stages:",
    "  - build",
    "  - verify",
    "  - deploy",
    "",
]


def quote_hosts(names: list[str]) -> str:
    return " ".join(names)


if x86 or gaming:
    hosts = x86 + gaming
    quoted = quote_hosts(hosts)
    lines += [
        "fill-attic:",
        "  extends: .fill-attic",
        "  variables:",
        f'    ATTIC_HOSTS: "{quoted}"',
        "",
        "verify-from-attic:",
        "  extends: .verify-from-attic",
        "  variables:",
        f'    ATTIC_HOSTS: "{quoted}"',
        "",
    ]

if deploy_flag and rpi4:
    lines += [
        "fill-attic-rpi4:",
        "  extends: .fill-attic-rpi4",
        "  variables:",
        '    ATTIC_HOSTS: "rpi4"',
        "",
        "verify-from-attic-rpi4:",
        "  extends: .verify-from-attic-rpi4",
        "  variables:",
        '    ATTIC_HOSTS: "rpi4"',
        "",
        "deploy-rpi4:",
        "  extends: .deploy-rpi4",
        "",
    ]

if deploy_flag:
    for host in x86:
        lines += [
            f"deploy-{host}:",
            "  extends: .deploy-host",
            "  environment:",
            f"    name: {host}",
            "",
        ]
    if gaming:
        lines += [
            "deploy-gaming:",
            "  extends: .deploy-host",
            "  environment:",
            "    name: gaming",
            "  when: manual",
            "  allow_failure: true",
            "",
        ]

has_jobs = bool(x86 or gaming) or (deploy_flag and bool(rpi4))
if not has_jobs:
    # rpi4 (and, on a branch, gaming/x86 fill jobs are still emitted above
    # if changed) may be sitting in the "changed" set with nothing to do
    # here only because deploy_flag is false (aarch64 fill/deploy is
    # main-only: docs/adr/2026-08-31-rpi4-native-build.md). Say so instead
    # of claiming nothing changed.
    if not deploy_flag and rpi4:
        message = (
            f"rpi4 toplevel changed ({', '.join(rpi4)}) but aarch64 fill "
            "runs only on main; nothing to do on this branch"
        )
    else:
        message = "No host toplevels changed; skipping fill, verify, and deploy"
    lines += [
        "no-hosts-changed:",
        "  stage: build",
        "  image: debian:trixie-slim",
        "  interruptible: true",
        "  before_script: []",
        "  script:",
        f'    - echo "{message}"',
        "",
    ]

text = "\n".join(lines)
if dest == "/dev/stdout":
    sys.stdout.write(text)
else:
    with open(dest, "w", encoding="utf-8") as f:
        f.write(text)
PY
